version: "3.3"


# Создается при первичной конфигурации `custom_config/MAKE_CONFIG.sh`
volumes:
  ovpn-data-container:
    external: true
  mongodb:

services:

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    #ports:
    #  - "27017:27017"
    env_file:
      - ./mongodb/credentials.env
    volumes:
      - mongodb:/data/db

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 4402:8081
    env_file:
      - ./mongodb/credentials.env
    volumes:
      - mongodb:/data/db

  ovpn_server:
    depends_on:
      - mongodb
    container_name: ovpn_server
    #image: kylemanna/openvpn
    image: deaffella/ovpn-fastapi
    build:
      context: ovpn
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
      - 4400:8000
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ./mongodb/credentials.env
    tty: true
    stdin_open: true
    hostname: ovpn_server
    volumes:
      - ovpn-data-container:/etc/openvpn
    command: '/bin/bash -c "ovpn_run & uvicorn main:app --host 0.0.0.0 --port 8000"'

  ovpn_monitor:
    depends_on:
      - ovpn_server
    container_name: ovpn_monitor
    image: ruimarinho/openvpn-monitor:d259fadd
    restart: always
    ports:
      - 4401:80
    environment:
      - TZ=Europe/Moscow
      - OPENVPNMONITOR_DEFAULT_LATITUDE=59.934378
      - OPENVPNMONITOR_DEFAULT_LONGITUDE=30.335423
      - OPENVPNMONITOR_DEFAULT_DATETIMEFORMAT="%%d/%%m/%%Y"
      - OPENVPNMONITOR_DEFAULT_MAPS=True
      - OPENVPNMONITOR_DEFAULT_MAPSHEIGHT=500
      - OPENVPNMONITOR_SITES_0_ALIAS=UDP
      - OPENVPNMONITOR_SITES_0_HOST=ovpn_server
      - OPENVPNMONITOR_SITES_0_NAME=UDP
      - OPENVPNMONITOR_SITES_0_PORT=5555
      - OPENVPNMONITOR_SITES_0_SHOWDISCONNECT=True
    tty: true
    stdin_open: true

  telegram_bot:
    depends_on:
      - mongodb
    container_name: telegram_bot
    image: deaffella/ovpn-telegram_bot
    build:
      context: telegram_bot
      dockerfile: Dockerfile
    restart: always
    #ports:
    #  - 1194:1194/udp
    #  - 4400:8000
    environment:
      - TZ=Europe/Moscow
      - API_URL=ovpn_server:8000
    env_file:
      - ./mongodb/credentials.env
    tty: true
    stdin_open: true
    volumes:
      - ./telegram_bot:/telegram_bot
      - ovpn-data-container:/ovpn
    secrets:
      - tg_bot
      #command: 'bash'
    entrypoint: 'bash'


secrets:
  tg_bot:
    file: telegram_bot/token.env.secret